/**
 * Person Types used in WLH environment
 */
export enum EPersonType {
  ADMIN = "ADMIN",
  ADVANCED_SEARCH_PERSON_TYPE = "ADVANCED_SEARCH_PERSON_TYPE",
  CONSULT = "CONSULT",
  DOCTOR = "DOCTOR",
  FAMILY_MEMBER = "FAMILY_MEMBER",
  INSURANCE_SUBSCRIBER = "INSURANCE_SUBSCRIBER",
  PM = "PRACTICE_MANAGER",
  MYCA = "MYCA",
  NOT_PATIENT = "NOT_PATIENT",
  PATIENT = "PATIENT",
  REFERRAL = "REFERRAL_PROVIDER",
  TEMPORARY = "TEMPORARY",
}
