import { IsEnum, IsString } from "class-validator";
import {
  IBaseCarePlanSnapshot,
  BaseCarePlanSnapshot,
} from "./BaseCarePlanSnapshot";

export enum ELifestyle {
  Smoking = "Smoking",
  Alcohol = "Alcohol",
  Nutrition = "Nutrition",
  PhysicalActivity = "PhysicalActivity",
}

export interface ICarePlanLifestyleSnapshot extends IBaseCarePlanSnapshot {
  lifestyleSnapshotId: string;
  data: string;
  lifestyleType: ELifestyle;
}

/**
 * This class represents a snapshot of a care plan lifestyle.
 * A lifestyle is a record of an individual's habits, behaviors, and physical characteristics.
 * This includes things like exercise, diet, and sleep patterns.
 *
 * @class CarePlanLifestyleSnapshot
 * @extends BaseCarePlanSnapshot
 *
 * @property {string} lifestyleSnapshotId - The ID of the lifestyle snapshot (generated by uuidv4)
 * @property {string} data - Data associated with the lifestyle snapshot
 * @property {ELifestyle} lifestyleType - The type of lifestyle associated with the snapshot (e.g. exercise, diet)
 *
 * @param {ICarePlanLifestyleSnapshot} data - Data used to create a new CarePlanLifestyleSnapshot instance
 *
 * @method serialize() - Serializes the instance into an object of type ICarePlanLifestyleSnapshot
 *
 * @example
 * const lifestyle = new CarePlanLifestyleSnapshot({
 *   lifestyleSnapshotId: uuidv4(),
 *   data: 'FHIR Observation stringified',
 *   lifestyleType: ELifestyle.Exercise
 * });
 */
export class CarePlanLifestyleSnapshot extends BaseCarePlanSnapshot {
  @IsString()
  lifestyleSnapshotId: string;

  @IsString()
  data: string;

  @IsEnum(ELifestyle)
  lifestyleType: ELifestyle;

  constructor(data: ICarePlanLifestyleSnapshot) {
    super(data);
    this.lifestyleSnapshotId = data.lifestyleSnapshotId;
    this.data = data.data;
    this.lifestyleType = data.lifestyleType;
  }

  public serialize(): ICarePlanLifestyleSnapshot {
    return {
      ...super.serialize(),
      lifestyleSnapshotId: this.lifestyleSnapshotId,
      data: this.data,
      lifestyleType: this.lifestyleType,
    };
  }
}
